# 基础设置
base:
  # 获取天气的城市
  city: 北京
  guide: true

# 服务器配置
server:
  # 启动地址（仅用于控制台输出）
  # auto 为自动获取IP地址
  host: auto
  # 启动端口号
  port: 50831
  # 是否需要拼接端口号
  splicePort: true

# jwt配置
jwt:
  # JWT 秘钥（随机生成，非必要请勿修改！）
  secret: ""
